%new qcon prototype.

runno='S66853rt';  % 
recon_vol=2; % the number of volumes to reconstruct. 
first_vol=2;

dx=512;
dy=256;
dz=256;

% to skip to firset desired recon add a load_skip.
% load_skip is block_header_size*(first_vol-1)+load_size*(first_vol-1)

bit_depth=32;  
%bit_depth=32;
data_type='float';
%data_type='float';

completed_volumes=7;
%recon_vol=completed_volumes-first_vol;% may need a +1...

block_skip=28;

vol_only_skip=(first_vol)*block_skip+(first_vol-1)*(2*dx*dy*dz*bit_depth/8);

rad_mat('kamy',runno,'../../../../home/vnmr1/vnmrsys/exp*/acqfil/fid', ...
{'ignore_kspace_oversize','testmode', ...
    'overwrite', 'existing_data',...
    'skip_mem_checks',...
    'ignore_errors', ...
    'U_dimension_order=xpyzct', ... % this changes off and on, it may require experimentation for a given data set.
    'no_scanner_header', ...
    'unrecognized_ok', ...
    'write_unscaled',...
    'S_PSDname=part_rec', ...
   ['A_kspace_bit_depth=' num2str(bit_depth)], ...
   ['A_kspace_data_type=' data_type], ...
   ['dim_X=' num2str(dx)], ['dim_Y=' num2str(dy)], ['dim_Z=' num2str(dz)], ...
    'ne=1', 'A_channels=1', ['A_volumes=' num2str(recon_vol) ], ...
   ['ray_blocks=' num2str(recon_vol)], ['ray_length=' num2str(dx)],[ 'rays_per_block=' num2str(dy*dz) ],['ray_blocks_per_volume=1'],...
   ['kspace_data_path=' getenv('BIGGUS_DISKUS') '/' runno '.work/fid'],...
    'puller_option_string=-f file',...
    'S_scanner_tag=A_',...
    'A_vol_type=4D',...
    'A_vol_type_detail=DTI7-single',...
    'A_kspace_endian=big',...
    'binary_header_size=32',... % this is the agilent file header length
   ['load_skip=' num2str(vol_only_skip)],...
   ['block_header_size=' num2str(block_skip)],... % this is the agilent block header length
    'U_prefix=z_Agilent_',...
    });

% 'existing_data', ...
% 'display_kspace'
